const buzos=[
    {
        marca: "VANS",
        color: "GRIS",
        talle: "16",
        images: "images/VANS1.webp",
        link: "https://www.vans.com.ar/buzos-hombre/#/?",
        price: "$68.990",
    },   
    {
        marca: "VANS",
        color: "NEGRO",
        talle: "S/L",
        images: "images/VANS2.webp",
        link: "https://www.vans.com.ar/buzos-hombre/#/?",
        price: "$64.799",
    },
    {
        marca: "VANS",
        color: "BLANCO",
        talle: "S/M/L",
        images: "images/VANS3.webp",
        link: "https://www.vans.com.ar/buzos-hombre/#/?",
        price: "$98.669",
    },
    {
        marca: "UNDEFINED",
        color: "NEGRO/VERDE",
        talle: "XS",
        images: "images/unde2.png",
        link:"https://undefinedba.com/?srsltid=AfmBOoqf-xsvEOoh8Hk7sG0Q0l8frGe0BgOvVdjCoIbl5YLsDWPLckoa",
        price:"$99.900",
    },
    {
        marca: "UNDEFINED",
        color: "NEGRO",
        talle: "M",
        images: "images/UNDEFINED2.jpg",
        link:"https://undefinedba.com/?srsltid=AfmBOoqf-xsvEOoh8Hk7sG0Q0l8frGe0BgOvVdjCoIbl5YLsDWPLckoa",
        price:"$39.950",
    },
    {
        marca: "UNDEFINED",
        color: "NEGRO",
        talle: "XS",
        images: "images/UNDEFINED3.jpg",
        link:"https://undefinedba.com/?srsltid=AfmBOoqf-xsvEOoh8Hk7sG0Q0l8frGe0BgOvVdjCoIbl5YLsDWPLckoa",
        price:"$92.900",
    },
    {
        marca: "NIKE",
        color: "NEGRO/GRIS",
        talle: "L",
        images: "images/nike1.webp",
        link:"https://www.nike.com.ar/_v/segment/routing/vtex.store@2.x/subcategory/10/nike/ropa/buzos?gad_source=1&gclid=EAIaIQobChMIgsLBmNrbiAMVjjcIBR01hgOREAAYASAAEgJxrvD_BwE&map=c,c,c&page=2",
        price:"$108.667,3",
    },
    {
        marca: "NIKE",
        color: "BEIGE/NARANJA",
        talle: "L",
        images: "images/nike2.jpg",
        link:"https://www.nike.com.ar/_v/segment/routing/vtex.store@2.x/subcategory/10/nike/ropa/buzos?gad_source=1&gclid=EAIaIQobChMIgsLBmNrbiAMVjjcIBR01hgOREAAYASAAEgJxrvD_BwE&map=c,c,c&page=2",
        price:"$122.569,3",
    },
    {
        marca: "NIKE",
        color: "VERDE",
        talle: "L",
        images: "images/nike3.jpg",
        link:"https://www.nike.com.ar/_v/segment/routing/vtex.store@2.x/subcategory/10/nike/ropa/buzos?gad_source=1&gclid=EAIaIQobChMIgsLBmNrbiAMVjjcIBR01hgOREAAYASAAEgJxrvD_BwE&map=c,c,c&page=2",
        price:"$122.569,3",
    },
    {
        marca: "ADIDAS",
        color: "NEGRO",
        talle: "L",
        images: "images/ADIDAS1.jpg",
        link:"https://www.adidas.com/us?clickId=RNVxAyyzWxyKWZOV6G2HcRM5UkCyhFWIv3W6VA0&irgwc=1&cm_mmc=AdieAffiliates_IR-_-Duomai.-_-adidas.com%20link-_-TEXT_LINK-_-&cm_mmc2=adidas-NA-eCom-Affiliates-_-Duomai.-_-None-None-US-always-on-None-1801&gad_source=1&gclid=EAIaIQobChMInurlotzbiAMV0TAIBR17-CNLEAAYAiAAEgLLbvD_BwE",
        price:"$72.000",
    },
    {
        marca: "ADIDAS",
        color: "VERDE",
        talle: "L",
        images: "images/ADIDAS2.webp",
        link:"https://www.adidas.com/us?clickId=RNVxAyyzWxyKWZOV6G2HcRM5UkCyhFWIv3W6VA0&irgwc=1&cm_mmc=AdieAffiliates_IR-_-Duomai.-_-adidas.com%20link-_-TEXT_LINK-_-&cm_mmc2=adidas-NA-eCom-Affiliates-_-Duomai.-_-None-None-US-always-on-None-1801&gad_source=1&gclid=EAIaIQobChMInurlotzbiAMV0TAIBR17-CNLEAAYAiAAEgLLbvD_BwE",
        price:"$83.000",
    },
    {
        marca: "ADIDAS",
        color: "BLANCO/NEGRO",
        talle: "L",
        images: "images/ADIDAS3.jpg",
        link:"https://www.adidas.com/us?clickId=RNVxAyyzWxyKWZOV6G2HcRM5UkCyhFWIv3W6VA0&irgwc=1&cm_mmc=AdieAffiliates_IR-_-Duomai.-_-adidas.com%20link-_-TEXT_LINK-_-&cm_mmc2=adidas-NA-eCom-Affiliates-_-Duomai.-_-None-None-US-always-on-None-1801&gad_source=1&gclid=EAIaIQobChMInurlotzbiAMV0TAIBR17-CNLEAAYAiAAEgLLbvD_BwE",
        price:"$82.999",
    },
    {
        marca: "ZARA",
        color: "MARRÓN",
        talle: "L",
        images: "images/ZARA1.jpg",
        link:"https://www.zara.com/ar/",
        price:"$89.990,00",
    },
    {
        marca: "ZARA",
        color: "BEIGE",
        talle: "L",
        images: "images/ZARA2.jpg",
        link:"https://www.zara.com/ar/",
        price:"$89.990,00",
    },
    {
        marca: "ZARA",
        color: "BLANCO",
        talle: "L",
        images: "images/ZARA3.jpg",
        link:"https://www.zara.com/ar/",
        price:"$89.990,00",
    },
    {
        marca: "AMERICAN EAGLE",
        color: "BEIGE OSCURO",
        talle: "L",
        images: "images/AE1.webp",
        link:"https://www.ae.com/intl/es",
        price:"$67.167,75",
    },
    {
        marca: "AMERICAN EAGLE",
        color: "MARRÓN",
        talle: "L",
        images: "images/AE2.webp",
        link:"https://www.ae.com/intl/es",
        price:"$67.167,75",
    },
    {
        marca: "AMERICAN EAGLE",
        color: "NEGRO",
        talle: "L",
        images: "images/AE3.webp",
        link:"https://www.ae.com/intl/es",
        price:"$67.167,75",
    },
    {
        marca: "ABERCROMBIE",
        color: "AZUL/BLANCO",
        talle: "L",
        images: "images/ABER1.webp",
        link:"https://www.abercrombie.com/shop/us-es",
        price:"273.900",
    },
    {
        marca: "ABERCROMBIE",
        color: "VERDE/AZUL",
        talle: "M",
        images: "images/ABER2.jpg",
        link:"https://www.abercrombie.com/shop/us-es",
        price:"$99.600",
    },
    {
        marca: "ABERCROMBIE",
        color: "GRIS",
        talle: "L",
        images: "images/ABER3.avif",
        link:"https://www.abercrombie.com/shop/us-es",
        price:"$99.600",
    },
    {
        marca: "BILLABONG",
        color: "BLANCO",
        talle: "L",
        images: "images/billa1.jpg",
        link:"https://www.billabong.com.ar/coleccion/hombres0003/buzos0005/?mpage=2",
        price:"$75.000,00",
    },
    {
        marca: "BILLABONG",
        color: "GRIS",
        talle: "L",
        images: "images/billa2.jpg",
        link:"https://www.billabong.com.ar/coleccion/hombres0003/buzos0005/?mpage=2",
        price:"$55.000",
    },
    {
        marca: "BILLABONG",
        color: "BEIGE OSCURO",
        talle: "L",
        images: "images/billa3.jpg",
        link:"https://www.billabong.com.ar/coleccion/hombres0003/buzos0005/?mpage=2",
        price:"$55.000$",
    },
    {
        marca: "COLUMBIA",
        color: "BEIGE",
        talle: "L",
        images: "images/COLUMBIA11.webp",
        link:"https://www.columbiasportswear.com.ar/?gad_source=1&gclid=EAIaIQobChMIgZ7j_OTbiAMVWkH_AR2fXwMUEAAYASAAEgI48_D_BwE",
        price:"$100.080,00",
    },
    {
        marca: "COLUMBIA",
        color: "ROJO",
        talle: "L",
        images: "images/COLUMBIA 22.webp",
        link:"https://www.columbiasportswear.com.ar/?gad_source=1&gclid=EAIaIQobChMIgZ7j_OTbiAMVWkH_AR2fXwMUEAAYASAAEgI48_D_BwE",
        price:"$100.080,00",
    },
    {
        marca: "COLUMBIA",
        color: "MARRÓN",
        talle: "L",
        images: "images/COLUMBIA33.webp",
        link:"https://www.columbiasportswear.com.ar/?gad_source=1&gclid=EAIaIQobChMIgZ7j_OTbiAMVWkH_AR2fXwMUEAAYASAAEgI48_D_BwE",
        price:"$100.080,00",
    },
    {
        marca: "RIPCURL",
        color: "GRIS",
        talle: "L",
        images: "images/RIP1.jpg",
        link:"https://www.ripcurlargentina.com/",
        price:"$29999",
    },
    {
        marca: "RIPCURL",
        color: "GRIS",
        talle: "L",
        images: "images/rip2.jpg",
        link:"https://www.ripcurlargentina.com/",
        price:"$79.990",
    },
    {
        marca: "RIPCURL",
        color: "CELESTE",
        talle: "L",
        images: "images/rip3.webp",
        link:"https://www.ripcurlargentina.com/",
        price:"$49.999,00",
    },
    {
        marca: "LEVIS",
        color: "VIOLETA",
        talle: "L",
        images: "images/LEVIS1.jpg",
        link:"https://www.levi.com.ar/?gad_source=1&gclid=EAIaIQobChMIj6b1qObbiAMVTFRIAB2z0Do_EAAYASAAEgJduvD_BwE",
        price:"$ 102.400",
    },
    {
        marca: "LEVIS",
        color: "NEGRO",
        talle: "L",
        images: "images/levis2.webp",
        link:"https://www.levi.com.ar/?gad_source=1&gclid=EAIaIQobChMIj6b1qObbiAMVTFRIAB2z0Do_EAAYASAAEgJduvD_BwE",
        price:"$111.200",
    },
    {
        marca: "LEVIS",
        color: "MARRÓN/ROJO",
        talle: "L",
        images: "images/levis3.webp",
        link:"https://www.levi.com.ar/?gad_source=1&gclid=EAIaIQobChMIj6b1qObbiAMVTFRIAB2z0Do_EAAYASAAEgJduvD_BwE",
        price:"$89.600",
    },
    {
        marca: "LACOSTE",
        color: "CREMA",
        talle: "L",
        images: "images/LACOSTÉ1.jpg",
        link:"https://www.lacoste.com/ar/lacoste/descubrir/tendencias/french-style-is-made-to-last/?gad_source=1&gclid=EAIaIQobChMIn6imzOjbiAMVkzIIBR2fVQ5wEAAYASAAEgL6BfD_BwE",
        price:"$210.000",
    },
    {
        marca: "LACOSTE",
        color: "VERDE",
        talle: "L",
        images: "images/LACOSTÉ2.jpg",
        link:"https://www.lacoste.com/ar/lacoste/descubrir/tendencias/french-style-is-made-to-last/?gad_source=1&gclid=EAIaIQobChMIn6imzOjbiAMVkzIIBR2fVQ5wEAAYASAAEgL6BfD_BwE",
        price:"$210.000", 
    },
    {
        marca: "LACOSTE",
        color: "GRIS",
        talle: "L",
        images: "images/LACOSTÉ3.jpg",
        link: "https://www.lacoste.com/ar/lacoste/descubrir/tendencias/french-style-is-made-to-last/?gad_source=1&gclid=EAIaIQobChMIn6imzOjbiAMVkzIIBR2fVQ5wEAAYASAAEgL6BfD_BwE",
        price:"$210.000",
    },
    {
        marca: "THE NORTH FACE",
        color: "VERDE",
        talle: "L",
        images: "images/NF1.jpg",
        link: "https://www.thenorthface.com.ar/?gad_source=1&gclid=EAIaIQobChMIh7H9rPPbiAMVOjIIBR05fyixEAAYASAAEgL3s_D_BwE",
        price:"$370.000",
    },
    {
        marca: "THE NORTH FACE",
        color: "NEGRO",
        talle: "L",
        images: "images/NF2.jpg",
        link: "https://www.thenorthface.com.ar/?gad_source=1&gclid=EAIaIQobChMIh7H9rPPbiAMVOjIIBR05fyixEAAYASAAEgL3s_D_BwE",
        price:"$370.000",
    },
    {
        marca: "THE NORTH FACE",
        color: "GRIS",
        talle: "L",
        images: "images/NF3.jpg",
        link: "https://www.thenorthface.com.ar/?gad_source=1&gclid=EAIaIQobChMIh7H9rPPbiAMVOjIIBR05fyixEAAYASAAEgL3s_D_BwE",
        price:"$250.000",
    },
{
    marca: "OVERSIZE",
    color: "ROSA",
    talle: "XL/XXL",
    images: "images/over1.jpg",
    link: "https://www.grafizona.com.ar/productos/buzo-canguro-honshin-estilo-japanese-art-grafizona/",
    price: "$65.000",
},
{
    marca: "OVERSIZE",
    color: "NEGRO",
    talle: "XL/XXL",
    images: "images/over2.jpg",
    link: "https://articulo.mercadolibre.com.ar/MLA-1425374755-buzo-canguro-the-creative-estilo-i-ching-aesthetic-grafizona-_JM?searchVariation=180435744586#polycard_client=search-nordic&searchVariation=180435744586&position=9&search_layout=grid&type=item&tracking_id=4ccb1910-2254-41ad-9893-3d02ce62a9ea",
    price: "$69.000",
},
{
    marca: "OVERSIZE",
    color: "NEGRO",
    talle: "XL/XXL",
    images: "images/over3.jpg",
    link: "https://www.tiendaderopaargentina.com/productos/buzo-moon-negro/",
    price: "$74.999,00",
},
{
    marca: "DEPORTIVOS",
    color: "NEGRO",
    talle: "L",
    images: "images/deportivo1.webp",
    link: "https://www.falabella.com/falabella-cl/product/123376069/Poleron-Buzo-Hombre-Rival-Terry-Logo-Hod-Negro-UNDER-ARMOUR/123376071",
    price: "$32.990",
},
{
    marca: "DEPORTIVOS",
    color: "NEGRO",
    talle: "S",
    images: "images/deportivo2.avif",
    link: "https://www.megasports.com.ar/puma-hoody-mujer---power-graphic-negro/p",
    price: "$29.849,00",
},
{
    marca: "DEPORTIVOS",
    color: "NEGRO",
    talle: "S/M",
    images: "images/deportivo3.jfif",
    link: "https://www.dexter.com.ar/buzo-entrenamiento-puma-concept-knit-hombre/PU524887-01.html",
    price: "$98.999",
},
{
    marca: "VINTAGE",
    color: "AZUL",
    talle: "M",
    images: "images/vintage1.jfif",
    link: "https://starlordclothesferia.empretienda.com.ar/camperas-anoraks/buzo-anorak-nike-retro-og",
    price: "$10.769,00",
},
{
    marca: "VINTAGE",
    color: "NEGRO",
    talle: "M",
    images: "images/vintage2.jpeg",
    link: "https://www.starlordclothes.com/buzos/buzo-adidas-retro-sport",
    price: "$9.680,00",
},
{
    marca: "VINTAGE",
    color: "VERDE/AMARILLO",
    talle: "M",
    images: "images/vintage3.jpg",
    link: "https://articulo.mercadolibre.com.ar/MLA-1527145500-buzo-kevingston-original-hombre-nuevo-rugby-bordado-adelante-_JM?searchVariation=178903846474#polycard_client=search-nordic&searchVariation=178903846474&position=7&search_layout=stack&type=item&tracking_id=8540d7b6-2a0a-4a8e-80fd-dd3951fcc231",
    price: "$80.000",
},
{
    marca: "SIN CAPUCHA",
    color: "BLANCO",
    talle: "XL",
    images: "images/sincapucha1.jpeg",
    link: "https://www.blossietienda.com/productos/buzo-sin-capucha-premium-man/",
    price: "$18.500,00",
},
{
    marca: "SIN CAPUCHA",
    color: "NEGRO",
    talle: "S",
    images: "images/sincapucha2.jpg",
    link: "https://www.onearthly.com.ar/productos/buzo-sin-capucha/",
    price: "$52.000",
},
{
    marca: "SIN CAPUCHA",
    color: "AZUL",
    talle: "S",
    images: "images/sincapucha2.jpg",
    link: "https://www.rpmcross.com/products/buzo-sin-capucha-outdoor-azul",
    price: "$54.500",
},
{
    marca: "EGRESADOS",
    color: "BLANCO",
    talle: "XL",
    images: "images/egresados1.jpg",
    link: "https://littleblue.com.ar/productos/buzos/buzo-canguro/buzo-batik",
    price: "$94.500",
},
{
    marca: "EGRESADOS",
    color: "VIOLETA",
    talle: "XL",
    images: "images/egresados2.jpg",
    link: "https://littleblue.com.ar/productos/buzos/buzo-canguro/buzo-batik",
    price: "$94.500",
},
{
    marca: "EGRESADOS",
    color: "MARRÓN/BLANCO",
    talle: "XL",
    images: "images/egresados3.jpg",
    link: "https://littleblue.com.ar/productos/buzos/buzo-canguro/buzo-batik",
    price: "$94.500",
},
{
    marca: "CHAQUETAS",
    color: "GRIS",
    talle: "XXL",
    images: "images/chaqueta1.jpg",
    link: "https://tiendamia.com/ar/producto?amz=B077LGGJ25",
    price: "$352.440",
},
{
    marca: "CHAQUETAS",
    color: "NEGRO",
    talle: "XXL",
    images: "images/chaqueta2.jpg",
    link: "https://www.amazon.es/Chaqueta-Cuero-para-Hombre-Impermeable/dp/B0BJ68SP4Z",
    price: "$120.960",
},
{
    marca: "CHAQUETAS",
    color: "MARRÓN",
    talle: "XXL",
    images: "images/chaqueta3.jpg",
    link: "https://www.cueroecuador.com/product/chaqueta-maverick-cuero-bovino/",
    price: "$156.440",
},
{
    marca: "CAMPERAS",
    color: "NEGRO",
    talle: "M/L",
    images: "images/campera1.webp",
    link: "https://articulo.mercadolibre.com.ar/MLA-1425282075-campera-hombre-abrigo-puffer-inflada-liviana-importadas-_JM",
    price: "$40.999",
},
{
    marca: "CAMPERAS",
    color: "VERDE",
    talle: "M/L",
    images: "images/campera2.webp",
    link: "https://www.novusindumentaria.com.ar/MLA-1688451380-campera-hombre-inflada-parka-larga-capucha-abrigada-invierno-_JM",
    price: "$127.300",
},
{
    marca: "CAMPERAS",
    color: "CELESTE",
    talle: "S",
    images: "images/campera3.jpg",
    link: "https://www.ligero.com.ar/productos/campera-de-pluma-hombre-celeste/",
    price: "$184.740",
},
{
    marca: "LEÑADORAS",
    color: "BLANCO/NEGRO",
    talle: "4/6",
    images: "images/leña1.jpg",
    link: "https://www.nanitas.com.ar/productos/camisa-lenadora-con-capucha/",
    price: "$9.704",
},
{
    marca: "LEÑADORAS",
    color: "BLANCO/CREMA",
    talle: "S",
    images: "images/leña2.jpg",
    link: "https://ntfcba.com.ar/productos/camisa-ntf-lenadora-con-capucha-jenna-beige-nat/",
    price: "$48.993",
},
{
    marca: "LEÑADORAS",
    color: "BLANCO/AZUL",
    talle: "S",
    images: "images/leña3.webp",
    link: "https://www.tabla.com.ar/productos/camisa-lenadora-5/",
    price: "$29.900",
},

{
    marca: "MASCULINO",
    color: "BEIGE OSCURO",
    talle: "SM",
    images: "images/hombre1.jpeg",
    link: "https://www.underarmour.com.ar/p/buzos_y_camperas/buzo_con_cuello_redondo_de_tejido_fleece_ua_rival_para_hombre/1357096.html",
    price: "$59,999.20",
},
{
    marca: "MASCULINO",
    color: "AZUL",
    talle: "S",
    images: "images/hombre2.webp",
    link: "https://articulo.mercadolibre.com.ar/MLA-1266815962-buzo-oversize-essentials-azul-con-capucha-hombre-algodon-_JM",
    price: "$15.999",
},
{
    marca: "MASCULINO",
    color: "NEGRO/BLANCO",
    talle: "S",
    images: "images/hombre3.webp",
    link: "https://articulo.mercadolibre.com.ar/MLA-1463221146-buzo-hombre-oversize-frisa-capucha-huoky-hard-_JM",
    price: "$29.990",
},
{
    marca: "MASCULINO",
    color: "MARRÓN",
    talle: "S/M/L/XL",
    images: "images/hombre4.jpg",
    link: "https://mockbaadrogue.mercadoshops.com.ar/MLA-1401225209-buzo-hombre-oversize-farenheite-by-mockba-search-blanco-_JM",
    price: "$48.900",
},
{
    marca: "MASCULINO",
    color: "BLANCO",
    talle: "M/L/XL",
    images: "images/hombre5.webp",
    link: "https://forever21.com.ar/buzo-hoodie-hombre-sherpa-forever21-r2t000098.html",
    price: "$56.000",
},
{
    marca: "FEMENINO",
    color: "NEGRO",
    talle: "L",
    images: "images/mujer1.jfif",
    link: "https://thisisbp.com/shop/product/112215016-buzo-con-capucha-mujer-black-umbria-28941#attr=54099,54101,54100,54270",
    price: "$42.704",
},
{
    marca: "FEMENINO",
    color: "ROJO",
    talle: "XS",
    images: "images/buzo2.jpg",
    link: "https://www.montagne.com.ar/producto/1662-buzo-de-mujer-layla",
    price: "$51.570,90",
},
{
    marca: "FEMENINO",
    color: "NEGRO",
    talle: "S/L/M",
    images: "images/mujer2.jpg",
    link: "https://www.columbiasportswear.com.ar/buzo-polar-columbia-glacial-iv-1-2-zip-fleece-mujer-black/p",
    price: "$70.014",
},
{
    marca: "FEMENINO",
    color: "MARRÓN",
    talle: "XL",
    images: "images/mujer3.jpg",
    link: "https://www.billabong.com.ar/productos/buzo-essential-over-hood1/",
    price: "$69.999",
},
{
    marca: "FEMENINO",
    color: "AZUL",
    talle: "2",
    images: "images/mujer4.jpeg",
    link: "https://www.amatistaswimwear.com/productos/buzo-over-azul/",
    price: "$35.000",
},
{
    marca: "UNISEX",
    color: "ROSA",
    talle: "XS/XXL",
    images: "images/unisex2.jpg",
    link: "https://www.underarmour.com.ar/p/unisex/buzo_con_capucha_ua_summit_knit_unisex/196040018805.html",
    price: "$90,999.35",
},
{
    marca: "UNISEX",
    color: "NEGRO",
    talle: "(ÚNICO)",
    images: "images/unisex4.jpg",
    link: "https://estampado.com.ar/productos/buzo-hoodie-corderito-unisex/",
    price: "$42.809",
},
{
    marca: "UNISEX",
    color: "NEGRO",
    talle: "XS/XL",
    images: "images/unisex5.avif",
    link: "https://www.adidas.com.ar/buzo-con-capucha-sportswear-manga-larga-unisex/IR5748.html",
    price: "$99.999",
},

]

function mostrarbuzos(misBuzos=buzos){
    const section= document.querySelector(".listado-buzos");
    let elementos="";
    misBuzos.forEach((buzo)=>{
    elementos+=`<div class="card">
    <img src="${buzo.images}">
    <p>${buzo.marca}</p>
    <p>${buzo.color}</p>
    <p>${buzo.talle}</p>
    <p>${buzo.price}</p>
    <p><a class="pagina" href="${buzo.link}">Página oficial</a></p>
    </div>`;
});
section.innerHTML=elementos;
}
function APLICARFILTRO(marca){
    const filtrarbuzos=buzos.filter((buzo)=>{
        const buzosFiltrados = buzo.marca==marca;
        return buzosFiltrados
    })
    mostrarbuzos(filtrarbuzos);
}
function SORTEO() {
    const nombre=document.getElementById("name").value;
    const email=document.getElementById("email").value;
    const telefono=document.getElementById("telefono").value;
    if(nombre=="" || email=="" || telefono==""){
        alert("Falta completar campos")
    } else{
        alert("Has sido inscripto correctamente")
    }
}